### ISSUE TITLE
no scrolling

### ISSUE THREAD

**Issue by mboles** [blairvanderhoof/gist-embed#49] opened 2016-03-16 18:37 UTC
Blair-
We have had issues that sometimes (I can't narrow the exact cause down, sorry) one cannot horizontally scroll the gist embed. You can see the issue on this page: http://docs.brightcove.com/en/video-cloud/mobile-sdks/brightcove-player-sdk-for-ios/guides/quick-start-swift.html. 

We do have other places on the site where scrolling does work: http://docs.brightcove.com/en/video-cloud/brightcove-player/getting-started/quick-start-bc-player.html#addplugin

We have discovered that if we don't hide the footer the problem goes away, but would rather not have the footer showing.

Thanks much-
Matt

**Comment by blairvanderhoof** [comment] 2016-03-17 00:43
I went to http://docs.brightcove.com/en/video-cloud/mobile-sdks/brightcove-player-sdk-for-ios/guides/quick-start-swift.html and am not sure which ones are supposed to be scrolling, can you show me a side by side of what it should look like vs. what the issue is?

**Comment by blairvanderhoof** [comment] 2016-07-07 02:05
@mboles Please let me know if i can help. Closing for now.

**Closed by blairvanderhoof** 2016-07-07 02:05 UTC
