### ISSUE TITLE
parsererror everywhere

### ISSUE THREAD

**Issue by mboles** [blairvanderhoof/gist-embed#21] opened 2014-04-30 17:01 UTC
Getting this in all uses 
"Failed loading gist https://gist.github.com/8759542.json: parsererror"

Same error on this page: 
http://blairvanderhoof.com/gist-embed/

**Comment by everettcaleb** [comment] 2015-05-27 00:37
This happens for me only on Safari/iOS clients...  Any ideas?

**Comment by blairvanderhoof** [comment] 2015-05-27 00:53
I was not able to reproduce but I have seen this issue before.  Seems to be something related to cookies with github.  Can you use network inspector to see the payload from the gist call?

**Comment by everettcaleb** [comment] 2015-05-27 00:55
Yeah, I'll take a look and tell you what I find.

**Comment by blairvanderhoof** [comment] 2015-05-27 18:59
Yea I just encountered this, my console:

Refused to execute script from 'https://gist.github.com/5457662.json?callback=jQuery191022874126979149878_1432753025894&_=1432753025895' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
blairvanderhoof.com/:1 Refused to execute script from 'https://gist.github.com/5457665.json?callback=jQuery191022874126979149878_1432753025898&_=1432753025899' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
blairvanderhoof.com/:1 Refused to execute script from 'https://gist.github.com/5457652.json?callback=jQuery191022874126979149878_1432753025896&_=1432753025897' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
blairvanderhoof.com/:1 Refused to execute script from 'https://gist.github.com/5457668.json?callback=jQuery191022874126979149878_1432753025900&_=1432753025901' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
blairvanderhoof.com/:1 Refused to execute script from 'https://gist.github.com/7922593.json?callback=jQuery191022874126979149878_1432753025902&_=1432753025903' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
http://blairvanderhoof.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by blairvanderhoof** [comment] 2015-05-27 19:04
Will reopen this as a reminder to investigate more.

**Comment by blairvanderhoof** [comment] 2015-08-18 16:06
I've not seen this in a while, closing for now.

**Closed by blairvanderhoof** 2015-08-18 16:06 UTC
